spring.application.name=firstDemoLearnSpring

# --- DB CONNECTION LOCAL ---
spring.datasource.url=jdbc:sqlserver://flashcard-sqlserver-anpk.database.windows.net:1433;databaseName=flashcard-database-anpk;encrypt=true;trustServerCertificate=false;
spring.datasource.username=PHUNGAN@flashcard-sqlserver-anpk
spring.datasource.password=Phung@n02122003

# --- MAIL CONFIG LOCAL (CHI DUNG DE TEST - KHONG COMMIT FILE NAY) ---
spring.mail.username=festavenue@gmail.com
spring.mail.password=dnavekrgsvcsdahb

# --- APP MAIL CONFIG ---
app.mail.from=festavenue@gmail.com
app.mail.verification-base-url=http://localhost:8080/api/auth/verify

# --- JWT CONFIG LOCAL ---
jwt.secret=ChuoiBiMatDaiNgoangDeKyTokenKhongTheDoanDuoc


